### ISSUE TITLE
Web essentials 2.6.13

### ISSUE THREAD

**Issue by msyahend** [madskristensen/WebEssentials2013#1935]
Hi Madkristensen,

i'm having issues after installing web essentials 2.6.13, it seems like im always getting .less compiling error. on my right side of the screen showing below:

/*

Compilation Error occurred (see error list to navigate to the error location):

*/

on output below im getting these errors, when saving .less file

5/08/2015 1:57:08 PM: LESS: Compiling _Variables.less
5/08/2015 1:57:09 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:10 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:10 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:10 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:11 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:11 PM: Looking for resource @ http://localhost.:17221/
5/08/2015 1:57:11 PM: Unable to find resource, aborting

![errors](https://cloud.githubusercontent.com/assets/13653626/9078093/226de5de-3b7a-11e5-8d1a-0fb8c4e3859c.JPG)

**Comment by kevingermain** [comment]
Hi, I had the same issue Today !!! I just disable my system proxy and It works now...

**Comment by alandraper** [comment]
I'm getting the same thing. It even happens on an empty .LESS file

![capture](https://cloud.githubusercontent.com/assets/13674761/9106746/5a474722-3bd7-11e5-8530-b335f6551833.PNG)

**Comment by alandraper** [comment]
I just installed Visual Studio 2013 Update 5, and the error no longer happening. Whew.

**Comment by msyahend** [comment]
Im gonna try this one

Mirza Syahendra
Computershare
Developer > Technology Services
P +61 3 9907 8183
Yarra Falls, 452 Johnston Street
Abbotsford VIC 3067, Melbourne, Australia
www.computershare.com.au<http://www.computershare.com.au/>

|  CERTAINTY  |  INGENUITY  |  ADVANTAGE  |

**Comment by msyahend** [comment]
still doesnt work, im very frustrated, cannot continue my work, is there any similar software like web essential ?

thank you in advance

**Comment by waynevaughan** [comment]
I get the following error:

8/8/2015 3:52:32 PM: SCSS: Compiling site.scss
8/8/2015 3:52:32 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:35 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:37 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:39 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:41 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:43 PM: Looking for resource @ http://localhost.:8526/
8/8/2015 3:52:46 PM: Unable to find resource, aborting
8/8/2015 3:52:46 PM: An exception was thrown when compiling C:\Users\Wayne\Documents\VS Projects\Tierion\trunk\Tierion.WebUI\Content\css\app\site.scss: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.GetPath(String sourceFileName, String targetFileName)
   at MadsKristensen.EditorExtensions.NodeExecutorBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.NodeCompilerRunner.<RunCompilerAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.CompilerRunnerBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.EditorCompilerInvoker.<InitiateCompilationAsync>d__4.MoveNext()
8/8/2015 3:52:46 PM: An exception was thrown when compiling C:\Users\Wayne\Documents\VS Projects\Tierion\trunk\Tierion.WebUI\Content\css\app\site.scss: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.GetPath(String sourceFileName, String targetFileName)
   at MadsKristensen.EditorExtensions.NodeExecutorBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Scss.ScssCompiler.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.NodeCompilerRunner.<RunCompilerAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.CompilerRunnerBase.<CompileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.Compilers.EditorCompilerInvoker.<InitiateCompilationAsync>d__4.MoveNext()

I've tried disabling system proxy and it doesn't work.

**Comment by mt-webdev** [comment]
Getting the same here.
I fixed it last week, by updateing my WE from update 4 to 5 even though i didnt upgrade my VS from update 4 to 5.
Maybe this "fix" helps some of you.
Opened VS today.... tried to create a new SCSS file -> error

**Comment by primenum** [comment]
I had the same error. 
Installing VS2013 update 5 and WE 2.6.13 does not solve the problem.
The issue in my case was "localhost." I'm using proxy server at work, thus this host should be in bypass list. 
Adding "localhost." to bypass proxy server local addresses, solve the issue

**Comment by msyahend** [comment]
thanks so much pimenum, it solved mine as well, we need to add localhost. into proxy list servers
